name: ehaba

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^8.0.6
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  flutter_bloc: ^7.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  rxdart: ^0.27.0
  file_picker: ^3.0.1
  font_awesome_flutter: ^9.0.0
  flutter_datetime_picker: ^1.5.1
  geolocator: ^7.0.3
  eva_icons_flutter: ^3.0.0
  extended_image: ^4.1.0
  timeago: ^3.0.2
  uuid: ^3.0.4
  flutter_launcher_icons: ^0.9.2
  google_nav_bar: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/profilephoto.png
    - assets/iconLogo.png
    - assets/iconHomePage.png
    - assets/tan01.jpg
    - assets/images/avata.png

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
          weight: 400